version: '3.8'

services:
  server:
    build: 
      context: ./server
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
  app:
    build:
      context: ./youtube-video-sharing
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodb-data: