version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - youtube-sharing-network
  app:
    build:
      context: ./youtube-sharing
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - youtube-sharing-network
    depends_on:
      - server
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - youtube-sharing-network

volumes:
  mongodb-data:

networks:
  youtube-sharing-network:
    driver: bridge
